language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

cache:
  directories:
    - vendor

before_script:
  - composer install --no-interaction

script:
  - composer run test

after_script:
  - php vendor/bin/coveralls -v

sudo: false